# Generated by Django 2.0.4 on 2018-07-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='photo',
            new_name='logo',
        ),
    ]
